### ISSUE TITLE
Identify the cause of the increased RMM memory usage

### ISSUE THREAD

**Issue by bokdeuk-jeong** [islet-project/islet#166]
We recently had to increase the heap size in RMM from 8MB to 16MB. 
Identify which module requires more memory for what purpose and how much it demands.

**Comment by nook1208** [comment]
I think it's good to make a memory stat feature to check the RMM memory status. 
Let me check the RMM code and then I'll push a PR for it

**Comment by nook1208** [comment]
I found that 'RMI::GRANULE_DELEGATE' command use RMM Heap memory the most.
I uploaded the memory stat result below wiki page: 
https://code.sec.samsung.net/confluence/display/SYSSECC/Stat

Let me finish #182 PR and then go further with RMI::GRANULE_DELEGATE command

**Comment by bokdeuk-jeong** [comment]
Could you share the result here? The link that you shared cannot be accessed in public.

**Comment by jinbpark** [comment]
This is mainly because,
we're managing GranuleStatusTable (GST) with a 2-level page table. (We manage RTT with a 3-level page table, that might be the reason why GST takes up a larger portion of memory than RTT)

One optimization for this is to use a 3-level page table for GST. But, to do so, https://github.com/Samsung/islet/issues/147 --> this refactoring task might be needed to get done first.
